default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_conf_development

test:
  <<: *default
  database: rails_conf_test

production:
  <<: *default
  database: rails_conf
